### ISSUE TITLE
Change Request: Remove Photo Size Limit

### ISSUE THREAD

**Issue by billypilgrim88** [CarSnoop-Inc/carsnoop-issues#211] opened 2023-03-24 16:00 UTC
Remove the photo size limit when a user is uploading photos, instead Taylor will create an endpoint that will reduce the file size before saving to S3:

<img width="1319" alt="Screenshot 2023-03-24 at 11 58 31 AM" src="https://user-images.githubusercontent.com/106979142/227578385-588a8fba-92dd-41be-adaa-8f8345e0ecee.png">

**Comment by Ryanb58** [comment] 2023-03-26 03:28
**PR:** https://github.com/CarSnoop-Inc/carsnoop-backend/pull/25

@YunchytsK @pozernishku @ssysoi @k-tratseuski 

Please review & push to dev for evaluation. Specifically test for .heic files(iphone images) if you can as I was unable to test this specific senario.

I was going to try to deploy to DEV, but decided against it as I am not familiar the changes made when the addition of PROD was added. And I don't want to step on anyones toes accidentally.

This change will probably require a FE change to increase the current file size to say 20MB or 30MB? 

Also... I think I may have noticed a bug with the existing `create_document` function within the databaseFunctions lambda.

@YunchytsK @pozernishku @ssysoi @k-tratseuski 

#### Possible Bug:

Within the `create_document` function it statically puts files into the `carsnoop` bucket. 
It seems someone was previously trying to upload `images` to the `carsnoop` bucket and `documents` into the `carsnoop-documents` bucket, but missed updating the `bucket_name` variable in the `put_object` function call. 

Might be something to look into, or if by design, no big deal. I just want to make sure we aren't putting sensitive documents into the public bucket.

Code:
https://github.com/CarSnoop-Inc/carsnoop-backend/blob/main/lambda_functions/databaseFunctions/lambda_function.py#L2227

**Comment by Ryanb58** [comment] 2023-03-30 05:33
Since the code within github was NOT **up-to-date**. I wrote a script to do that work for us.. and put it into the carsnoop-backend repo. 

I then ran the updater.. and re-applied my changes for the convert_and_compress functionality in the following PR.

I also updated the script to handle `heic` files and added some sample files for testing with under the `lambda_functions/databaseFunctions/test_files/` folder.

https://github.com/CarSnoop-Inc/carsnoop-backend/pull/30

This PR is not complete though, as I have not had the time to look through the updated `lambda_handler` file to put it into the proper spots. My original changes to that file were unable to be migrated as there were so many differences.

@k-tratseuski said something about possibly doing some of this with the FE, so feel free to ping me if you'd like me to pursue this implementation any further. I'll leave it as-is and not merged until I am instructed to do anything further.

**Comment by k-tratseuski** [comment] 2023-03-30 09:24
@Ryanb58 @billypilgrim88. We've decided to do it on FE side because of multiple reasons:
1) Because with our current approach with file uploading will not work for big files (we receive content length exceeded error)
2) Because this compressing and converting will dramatically increase lambda execution
3) Because previous version of @Ryanb58's code wasn't support heic and dmg files
4) Because doing these on FE side is faster to deliver (we already have such functionality)

We could have @Ryanb58 PR open in case we want to refactor our image uploading flow in future

**Comment by ssysoi** [comment] 2023-03-30 16:28
@billypilgrim88 Jon, it's ready. You can test it on dev env:
https://shop-dev.carsnoop.com/
After your approval we will make it on production env.

**Comment by Ryanb58** [comment] 2023-03-30 21:02
@ssysoi I wasn't able to select an `.heic` file from my laptop. Is that intentional?

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/3086302/228963877-e256881f-a693-4a94-9f26-3598960ff69c.png">

**Comment by k-tratseuski** [comment] 2023-03-31 07:27
@Ryanb58 you need to click show options and select "all files"
![image](https://user-images.githubusercontent.com/117080223/229052647-84e0fc11-ac96-4c84-a3f4-2c9a3a3e37ab.png)
But anyways I think we can fix that on FE side to have it for default

**Comment by vitalik77795** [comment] 2023-03-31 08:31
@billypilgrim88 I have a question for you. Has something changed with the caching settings? Because we've noticed some issues with caching.  Could you send me a distribution id, I will check cache invalidation process? So, if you'll have the same problem you can just use hard refresh.

**Closed** 2023-04-03 13:16 UTC
